language: php
php:
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"
before_script:
  - composer install --dev

## Run on container environment
sudo: false

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache
